### ISSUE TITLE
[Question] Will this be able to support other games beside Melee.

### ISSUE THREAD

**Issue by ProfElements** [project-slippi/project-slippi#25]
If so, how will it be done?

**Comment by nachoverdon** [comment]
No. Slippi works by patching the game so that it reads/write very specific in-game data. Without access to the source code, this had to be done with ASM. Only after _years of research_ was this project possible.

**Comment by JLaferri** [comment]
If you mean replays and such, no it will not work with any other games unless somebody else extends the concept for other games.

**Comment by JCMullis1** [comment]
personally would love something like slippi for a game like F Zero GX, netplay just isn't super viable
