### ISSUE TITLE
Playback fail when using the same file

### ISSUE THREAD

**Issue by Armastardo** [project-slippi/project-slippi#26]
If I try to load two segments from the same .slp file, the emulator will just stuck on "Waiting for game..." after the first one. This doesn't work:

`{
"mode":"queue",
"replay":"",
"isRealTimeMode":false,
"queue":[
{"startFrame":1000,"endFrame":1500,"path":"path/to/replay1"},
{"startFrame":2000,"endFrame":2500,"path":"path/to/replay1"}]}
{"startFrame":2000,"endFrame":2500,"path":"path/to/replay2"}]}`

But if I shuffle the replays in the json files it loads it properly. This works:

`{
"mode":"queue",
"replay":"",
"isRealTimeMode":false,
"queue":[
{"startFrame":1000,"endFrame":1500,"path":"path/to/replay1"},
{"startFrame":2000,"endFrame":2500,"path":"path/to/replay2"}]}
{"startFrame":2000,"endFrame":2500,"path":"path/to/replay1"}]}`}

I'm on the latest version and running "dolphin -i path/to/file.json"

**Comment by NikhilNarayana** [comment]
This has been fixed as of bf81c65
