### ISSUE TITLE
ASM License

### ISSUE THREAD

**Issue by EIREXE** [project-slippi/project-slippi#28]
It seems like the ASM code doesn't have a license, would it be possible to add one to it to have a fully open source codebase?

Cheers.

**Comment by namtsui** [comment]
> Who works on Slippi?
> 
> A large part of the project is open source and there have been a handful of notable contributors throughout Slippi's development. That said, we have organically established somewhat of a core team.

Also, can you clarify what parts of the project are open source and what parts are not?

**Comment by NikhilNarayana** [comment]
ASM code has now been licensed under GPL-3.0

https://github.com/project-slippi/slippi-ssbm-asm/commit/f2757cf5114e081a7d7eb0a84237a5f4925195e6
