### ISSUE TITLE
Stuck on blackscreen on startup

### ISSUE THREAD

**Issue by wheetboi** [project-slippi/project-slippi#29]
![image](https://user-images.githubusercontent.com/77525741/104799325-703c4200-578b-11eb-84ba-85832f936105.png)

Hi, I cannot launch the game as it goes to this black screen each time. 

Here are my attempted solutions that have so far not worked:

- Tried each video backend
- Restart PC
- Reinstall Dolphin
- Tried on FM, also did not work
- Tried on main drive and separate drive
- Updated VC run time
- Updated graphic drivers

I would appreciate any help towards this, please let me know if there's any more info needed.

**Comment by NikhilNarayana** [comment]
please use support channels in our discord

**Comment by wheetboi** [comment]
I did but no one has the answer. Do I really have to go back and reask at different times of the day until I find someone who does?

**Comment by NikhilNarayana** [comment]
> I did but no one has the answer. Do I really have to go back and reask at different times of the day until I find someone who does?

generally we have really good response times, so yeah i would suggest just asking again if nobody responds.

**Comment by klee-zus** [comment]
Was a solution to this problem ever found? I'm having the exact same issue and just like op I've been ignored on the discord.
